name: build-deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    if: contains( github.ref, 'main')
    runs-on: ubuntu-latest
    container:
      image: ryts/buildpnpm:latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: pnpm-deps
          restore-keys: pnpm-deps
      - name: install deps and build
        run: |
          pnpm install --prefer-offline
          pnpm run assets
          pnpm build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
